coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/ResponseDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPatchCouponInfosByIdStatusDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPostCouponInfosDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPostCouponValidateDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPostCouponsIssueDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPutCouponInfosByIdDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/PageInfoDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResGetCouponInfosByIdDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResGetCouponInfosDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResGetDailyCouponStatisticsDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResGetUserCouponsDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResPostCouponInfosDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/res/ResPostCouponValidateDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/Coupon.java, coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponInfo.java, coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponStatus.java, coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponType.java, coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponController.java, coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponInfoController.java, coupon/src/main/resources/application.properties, coupon/src/main/resources/application.yml
- feature/7/coupon-controller-dto-dummy-> develop
- Resolves #7 
- CouponController, Dto 생성 및 더미데이터 리턴 구현
- CouponInfoController, Dto 생성 및 더미데이터 리턴 구현
- Coupon, CouponInfo Entity 구현
=> Coupon 서비스 Controller. Dtop, Entity 및 더미데이터 리턴 구현

product/src/main/java/com/sparta/hotdeal/product/application/dtos/ResponseDto.java, product/src/main/java/com/sparta/hotdeal/product/application/dtos/product/ResGetProductDto.java, product/src/main/java/com/sparta/hotdeal/product/application/dtos/product/ResGetPromotionDto.java, product/src/main/java/com/sparta/hotdeal/product/application/dtos/product/ResProductIdDto.java, product/src/main/java/com/sparta/hotdeal/product/application/dtos/product/ResPromotionIdDto.java, product/src/main/java/com/sparta/hotdeal/product/application/dtos/review/ResGetReviewByIdDto.java, product/src/main/java/com/sparta/hotdeal/product/application/service/ProductService.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/AuditingDate.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/ProductCategoryEnum.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/ProductStatusEnum.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/File.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Product.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/ProductCategoryEnum.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/ProductStatusEnum.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Promotion.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/SubFile.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/AuditConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/SecurityConfig.java, product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ProductController.java, product/src/main/java/com/sparta/hotdeal/product/presentation/controller/PromotionController.java, product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ReviewController.java, product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPatchUpdateProductStatusDto.java, product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPostCreateProductDto.java, product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPostCreatePromotionDto.java, product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPutUpdateProductDto.java, product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/product/ReqPutUpdatePromotionDto.java, product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/review/ReqPostReviewDto.java, product/src/main/java/com/sparta/hotdeal/product/presentation/dtos/review/ReqPutReviewDto.java, product/src/main/resources/application.properties, product/src/main/resources/application.yml
- feature/6/review-controller-dto-dummy -> develop
- Resolves #6
- Product 브랜치 위에 작업했습니다 :) 
=> Review 서비스 Controller, DTO 생성 및 더미데이터 리턴 구현

gateway/build.gradle, gateway/src/main/resources/application.properties, gateway/src/main/resources/application.yml, server/src/main/java/com/sparta/hotdeal/server/ServerApplication.java, server/src/main/resources/application.properties, server/src/main/resources/application.yml
- feature/16/server-gateway-settings -> develop
- resolves #16 
- Eureka Server application.yml 업데이트 및 서버 활성화
- Gateway application.yml 업데이트 및 각 서비스 연결
실수로 application.yml 업데이트 커밋 타입을 chore가 아닌 feat로 했습니다... 다음부터는 주의하겠습니다.
=> Eureka Server 및 Gateway 세팅, 각 서비스 연결

user/src/main/java/com/sparta/hotdeal/user/application/dtos/ResponseMessage.java, user/src/main/java/com/sparta/hotdeal/user/application/dtos/users/request/ReqPatchUsersPasswordByIdDto.java, user/src/main/java/com/sparta/hotdeal/user/application/dtos/users/response/ResGetUsersByIdDto.java, user/src/main/java/com/sparta/hotdeal/user/application/exception/ErrorMessage.java, user/src/main/java/com/sparta/hotdeal/user/application/service/UserService.java, user/src/main/java/com/sparta/hotdeal/user/domain/entity/User.java, user/src/main/java/com/sparta/hotdeal/user/domain/repository/UserRepository.java, user/src/main/java/com/sparta/hotdeal/user/presentation/controller/UserController.java
- feature/26/crud-user -> develop
- Resolves #26 
- 회원조회 기능 구현
- 회원정보수정 기능 구현
- 비밀번호수정 기능 구현
- 회원탈퇴 기능 구현 
- 권한처리 관련 로직은 Gateway 코드 작성 후 추가할 예정입니다.
=> User 조회, 수정, 삭제 구현

coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/ErrorResponseDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPatchCouponInfosByIdStatusDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPostCouponInfosDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/dto/req/ReqPutCouponInfosByIdDto.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/CustomException.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/ErrorCode.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/GlobalExceptionHandler.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/mapper/CouponInfoMapper.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponInfoService.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponService.java, coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponInfo.java, coupon/src/main/java/com/sparta/hotdeal/coupon/domain/repository/CouponInfoRepository.java, coupon/src/main/java/com/sparta/hotdeal/coupon/domain/repository/CouponRepository.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/AuditConfig.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/SecurityConfig.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/custom/RequestUserDetails.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/custom/SecurityAuditorAware.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/ApplicationErrorCode.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/ApplicationException.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/handler/CustomAccessDeniedHandler.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/exception/handler/GlobalExceptionHandler.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/filter/AuthenticationFilter.java, coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponController.java, coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponInfoController.java
- feature/15/crud-couponInfo -> develop
- Resolves #15 
- 쿠폰 정보 CRUD
- 선착순 쿠폰 발급 구현
- Security 필터 구현 (현재 지수님 코드 복사해 온 상태 추후 수정 필요)
- Service 로직들에서 발생하는 예외들 CustomExeption으로 처리
- Security 쪽 코드 복사 해 오기 전에 서비스 로직 에러 처리 용도로 ErrorCode와 CustomException을 Application 위치에 만들어 사용 중이 었습니다.. 시큐리티 쪽 예외 처리와 같은 곳에서 처리하는 게 나을까요 아니면 용도가 다르니 지금처럼 서로 분리해두고 사용하는게 좋을까요??
=> 쿠폰 정보 CRUD, 선착순 쿠폰 발급 구현, 예외 처리, security 구현

user/src/main/java/com/sparta/hotdeal/user/application/dtos/ResponseMessage.java, user/src/main/java/com/sparta/hotdeal/user/application/dtos/address/request/ReqPostAddressDto.java, user/src/main/java/com/sparta/hotdeal/user/application/dtos/address/response/ResGetAddressByIdDto.java, user/src/main/java/com/sparta/hotdeal/user/application/dtos/address/response/ResGetAddressesDto.java, user/src/main/java/com/sparta/hotdeal/user/application/dtos/address/response/ResGetDefaultAddressDto.java, user/src/main/java/com/sparta/hotdeal/user/application/exception/ErrorMessage.java, user/src/main/java/com/sparta/hotdeal/user/application/service/AddressService.java, user/src/main/java/com/sparta/hotdeal/user/domain/entity/Address.java, user/src/main/java/com/sparta/hotdeal/user/domain/entity/User.java, user/src/main/java/com/sparta/hotdeal/user/domain/repository/AddressRepository.java, user/src/main/java/com/sparta/hotdeal/user/infrastructure/config/SecurityConfig.java, user/src/main/java/com/sparta/hotdeal/user/infrastructure/filter/AuthenticationFilter.java, user/src/main/java/com/sparta/hotdeal/user/infrastructure/repository/AddressRepositoryImpl.java, user/src/main/java/com/sparta/hotdeal/user/infrastructure/security/RequestUserDetails.java, user/src/main/java/com/sparta/hotdeal/user/presentation/controller/AddressController.java
- feature/35/crud-address -> develop
- Resolves #35 
- 배송지 등록 구현
- 배송지 조회(단건) 구현
- 기본 배송지 조회 구현
- 배송지 목록 조회 구현
- 배송지 수정 구현
- 기본 배송지 설정 구현
- 배송지 삭제 구현
- Security filter 및 UserDetails 구현
- filter에서 헤더를 가져와 UserDetails가 생성되는 것을 확인했습니다.
- 에러 응답 dto나 exception 위치 등 리팩토링은 이후 이슈를 새로 생성해 진행하겠습니다.
=> Address CRUD 및 Security 구현

user/build.gradle, user/src/main/java/com/sparta/hotdeal/user/application/dtos/auth/request/ReqPostCheckEmailDto.java, user/src/main/java/com/sparta/hotdeal/user/application/dtos/auth/request/ReqPostConfirmEmailDto.java, user/src/main/java/com/sparta/hotdeal/user/application/dtos/auth/request/ReqPostSignUpDto.java, user/src/main/java/com/sparta/hotdeal/user/application/dtos/auth/request/ReqPostVerifyEmailDto.java, user/src/main/java/com/sparta/hotdeal/user/application/exception/GlobalExceptionHandler.java, user/src/main/java/com/sparta/hotdeal/user/application/service/AuthService.java, user/src/main/java/com/sparta/hotdeal/user/application/service/UserService.java, user/src/main/java/com/sparta/hotdeal/user/domain/entity/Audit.java, user/src/main/java/com/sparta/hotdeal/user/infrastructure/filter/AuthenticationFilter.java, user/src/main/java/com/sparta/hotdeal/user/infrastructure/security/SecurityAuditorAware.java, user/src/main/java/com/sparta/hotdeal/user/presentation/controller/AuthController.java, user/src/main/java/com/sparta/hotdeal/user/presentation/controller/UserController.java, user/src/main/resources/application.yml
- feature/45/refactor-user -> develop
- Resolves #45 
- Audit 필드(createdBy 등) userId에서 email로 변경
- UserDetails 적용 필요한 부분 로직 변경(검증 등)
- 회원가입 시 dto에 valid 어노테이션 추가
- Gateway 연결 및 테스트
- filter에 필터를 수행하지 않을 경로 추가
- 1차 리팩토링 진행했습니다.
=> User 서비스 리팩토링(Audit, UserDetails 등)

product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/product/ReqPatchProductQuantityDto.java, product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/promotion/ReqPromotionQuantityDto.java, product/src/main/java/com/sparta/hotdeal/product/application/exception/ErrorCode.java, product/src/main/java/com/sparta/hotdeal/product/application/service/ProductPromotionHelperService.java, product/src/main/java/com/sparta/hotdeal/product/application/service/ProductService.java, product/src/main/java/com/sparta/hotdeal/product/application/service/PromotionService.java, product/src/main/java/com/sparta/hotdeal/product/domain/repository/product/ProductRepository.java, product/src/main/java/com/sparta/hotdeal/product/domain/repository/product/PromotionRepository.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/AuditConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/SecurityConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/custom/RequestUserDetails.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/custom/SecurityAuditorAware.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/exception/handler/CustomAuthenticationHandler.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/filter/AuthenticationFilter.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryCustom.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryImpl.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryJpa.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryImpl.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryJpa.java, product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ProductController.java, product/src/main/java/com/sparta/hotdeal/product/presentation/controller/PromotionController.java, product/src/main/resources/application.yml
- refactor/36/update-product,promotion -> develop
- Resolves #36 
- 상품 재고 수량 감소 하는 api 수정
- 상품 재고 수량 복구 하는 api 수정
- 상품 재고 수량 감소할 때 타임세일 재고 수량도 함께 감소하도록 수정
- 상품 재고 수량 복구할 때 타임세일 재고 수량도 함께 복구하도록 수정
- security 필터 구현
=> Product 수량 감소, 수량 복구 하는 로직 수정 및 Security 필터 구현

product/src/main/java/com/sparta/hotdeal/product/ProductApplication.java, product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/product/ReqPatchProductQuantityDto.java, product/src/main/java/com/sparta/hotdeal/product/application/dtos/req/promotion/ReqPromotionQuantityDto.java, product/src/main/java/com/sparta/hotdeal/product/application/exception/ErrorCode.java, product/src/main/java/com/sparta/hotdeal/product/application/scheduler/PromotionScheduler.java, product/src/main/java/com/sparta/hotdeal/product/application/service/ProductPromotionHelperService.java, product/src/main/java/com/sparta/hotdeal/product/application/service/ProductService.java, product/src/main/java/com/sparta/hotdeal/product/application/service/PromotionSchedulerService.java, product/src/main/java/com/sparta/hotdeal/product/application/service/PromotionService.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Product.java, product/src/main/java/com/sparta/hotdeal/product/domain/repository/product/ProductRepository.java, product/src/main/java/com/sparta/hotdeal/product/domain/repository/product/PromotionRepository.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/AuditConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/SecurityConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/custom/RequestUserDetails.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/custom/SecurityAuditorAware.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/exception/handler/CustomAuthenticationHandler.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/filter/AuthenticationFilter.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryCustom.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryImpl.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductRepositoryJpa.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryImpl.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/promotion/PromotionRepositoryJpa.java, product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ProductController.java, product/src/main/java/com/sparta/hotdeal/product/presentation/controller/PromotionController.java, product/src/main/resources/application.yml
- feature/54/scheduler-product -> develop
- Resolves #54 
- start 시간 확인하여 p_promotion.status, p_product.discountPrice 변경하는 스케줄러 구현
- end 시간 확인하여 p_promotion.status, p_product.discountPrice 변경하는 스케줄러 구현
- 스케줄러가 동작할 때 SecurityAuditorAware 에서 사용자를 찾지 못하는 문제가 발생하여, 인증 정보가 없을 때는 "SYSTEM"을 반환하도록 수정하였습니다.
=> Promotion 상태 변경하는 스케줄러 구현

company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ReqPatchCompanyByIdDto.java, company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ReqPatchCompanyByIdStatusDto.java, company/src/main/java/com/sparta/hotdeal/company/application/dtos/company/ReqPostCompanyDto.java, company/src/main/java/com/sparta/hotdeal/company/domain/entity/Audit.java, company/src/main/java/com/sparta/hotdeal/company/domain/entity/company/Company.java, company/src/main/java/com/sparta/hotdeal/company/infrastructure/config/SecurityConfig.java, company/src/main/java/com/sparta/hotdeal/company/infrastructure/exception/CustomAuthenticationHandler.java, company/src/main/java/com/sparta/hotdeal/company/infrastructure/filter/AuthenticationFilter.java, company/src/main/java/com/sparta/hotdeal/company/infrastructure/security/RequestUserDetails.java, company/src/main/java/com/sparta/hotdeal/company/infrastructure/security/SecurityAuditorAware.java, company/src/main/java/com/sparta/hotdeal/company/presentation/controller/CompanyController.java
- feature/49/refactor-company
- Resolves #49 
- Company Request Dto에 유효성 메세지 추가
- Security 인증을 위한 코드 추가
- Controller 권한 설정
=> Company 유효성 메세지 추가, Security 필터, 권한 구현

user/src/main/java/com/sparta/hotdeal/user/application/service/AuthService.java
인증 요청 시 Email Entity가 저장되지 않는 문제 수정
- fix/63/fix-send-email-user -> develop
- Resolves #63 
- 이메일 인증 시 Email Entity가 존재하지 않으면 Email Entity를 저장하도록 버그 수정
- 이메일 엔티티가 저장되지 않는 버그 수정입니다.
=> fix: 이메일 인증 버그 수정

user/build.gradle, user/src/main/java/com/sparta/hotdeal/user/infrastructure/config/SwaggerConfig.java, user/src/main/java/com/sparta/hotdeal/user/infrastructure/filter/AuthenticationFilter.java, user/src/main/resources/application-local.yml
- feature/71/swagger-user -> develop
- Resolves #71
- User Swagger Config 추가
- Swagger 경로는 필터를 수행하지 않도록 변경
- Swagger 추가 및 필터 제외 경로에 추가했습니다.
=> User 서비스 Swagger 적용

gateway/build.gradle, gateway/src/main/java/com/sparta/hotdeal/gateway/filter/AuthenticationFilter.java, gateway/src/main/resources/application-local.yml, gateway/src/main/resources/application-prod.yml, gateway/src/main/resources/application.yml
- refactor/72/swagger-filter-gateway -> develop
- Resolves #72
- Gateway filter를 수행하지 않을 경로에 Swagger 경로 추가
- application.yml에 swagger 및 RewritePath 설정 추가
- 스웨거 관련 설정 업데이트입니다.
=> Gateway filter Swagger 경로 추가

product/build.gradle, product/src/main/java/com/sparta/hotdeal/product/ProductApplication.java, product/src/main/java/com/sparta/hotdeal/product/application/exception/ErrorCode.java, product/src/main/java/com/sparta/hotdeal/product/application/service/ReviewService.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/client/CompanyClient.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/CompanyClientConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/SwaggerConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/exception/decoder/CompanyClientErrorDecoder.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/filter/AuthenticationFilter.java, product/src/main/java/com/sparta/hotdeal/product/presentation/controller/ProductController.java, product/src/main/java/com/sparta/hotdeal/product/presentation/controller/PromotionController.java, product/src/main/resources/application.yml
- feature/59/refactor-product,promotion -> develop
- Resolves #59 
- Product 서비스 Swagger 적용
- Product, Promotion 시큐리티 이용한 권한 검증 적용
=> Product 서비스 Swagger 적용 및 리팩토링

gateway/src/main/java/com/sparta/hotdeal/gateway/filter/AuthenticationFilter.java, gateway/src/main/resources/application.yml
- refactor/77/filter-gateway-1 -> develop
- Resolves #77 
- 필터를 수행하지 않을 경로 체크를 메서드로 분리
- payment, product, promotion, review 경로 추가
- 말씀해주신 경로들을 필터를 수행하지 않도록 추가했습니다.
- 체크하는 메서드는 나중에 경로를 Enum으로 분리해서 관리해볼 생각입니다.
=> Gateway에 필터를 수행하지 않을 경로 추가(payment, product, review)

company/build.gradle, company/src/main/java/com/sparta/hotdeal/company/application/dtos/ErrorResponseDto.java, company/src/main/java/com/sparta/hotdeal/company/infrastructure/config/SwaggerConfig.java, company/src/main/java/com/sparta/hotdeal/company/infrastructure/filter/AuthenticationFilter.java, company/src/main/java/com/sparta/hotdeal/company/presentation/controller/CompanyController.java, company/src/main/resources/application.yml
- feature/60/swagger-company
- Resolves #60 
- Company 도메인 Swagger 적용 및 필터 수정
=> Company 도메인 Swagger 적용 및 필터 수정

coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponInfoService.java
-fix/75/coupon-info-uri -> develop
- Resolves #75 
- uri 변경 누락된 부분도 변경
=> couponInfos URI 를 coupon-infos 로 누락된 부분도 수정

coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponInfoService.java, coupon/src/main/resources/application.yml
- fix/75/coupon info null check -> develop
- Resolves #75 
- yml에 admin 계정 환경변수 추가
- 쿠폰info 생성 시에 company null 분기처리
=> 쿠폰 info 생성 시 company null 분기처리

product/src/main/java/com/sparta/hotdeal/product/infrastructure/filter/AuthenticationFilter.java
- feature/59/refactor-product -> develop
- Resolves #59 
- AuthenticationFilter 수정
=> Product 서비스 AuthenticationFilter 수정

gateway/src/main/java/com/sparta/hotdeal/gateway/filter/AuthenticationFilter.java, gateway/src/main/resources/application.yml
- refactor/77/filter-gateway-1 -> develop
- Resolves #77 
- /api/v1/payment 경로 /api/v1/payments로 수정
- /api/v1/couponInfos 경로 /api/v1/coupon-infos로 수정
- 경로 변경 반영했습니다.
=> Gateway에 필터를 수행하지 않을 경로 수정

product/src/main/java/com/sparta/hotdeal/product/application/exception/ErrorCode.java, product/src/main/java/com/sparta/hotdeal/product/application/service/ReviewService.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/client/OrderClient.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/client/UserClient.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/OrderClientConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/UserClientConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/exception/decoder/OrderClientErrorDecoder.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/exception/decoder/UserClientErrorDecoder.java
- feature/87/review-feign-client-user
- Resolves #87 
- Review 도메인 User feign client 적용 및 로그 추가
=> Review 도메인 User feign client 적용 및 로그 추가

order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderBasketService.java, order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java, order/src/main/java/com/sparta/hotdeal/order/domain/repository/BasketRepository.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/CouponClientAdapter.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/ProductClient.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/SwaggerConfig.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/coupon/req/ReqPostCouponValidateDto.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/filter/AuthenticationFilter.java, order/src/main/java/com/sparta/hotdeal/order/presentation/controller/BasketController.java, order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java, order/src/main/resources/application.yml
- refactor/79/client-swagger-order -> develop
- Resolves #79 
- 주문 생성 Product, Coupon feignClient 수정
- 주문 서비스 Swagger 추가
=> Order feignClient 리팩토링 및 Swagger 추가

order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/req/ReqPutOrderDto.java, order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderBasketService.java, order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java, order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/Order.java, order/src/main/java/com/sparta/hotdeal/order/domain/entity/order/OrderStatus.java, order/src/main/java/com/sparta/hotdeal/order/domain/repository/BasketRepository.java, order/src/main/java/com/sparta/hotdeal/order/domain/repository/OrderRepository.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/CouponClientAdapter.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/client/ProductClient.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/ProductClientConfig.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/config/SwaggerConfig.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/dtos/coupon/req/ReqPostCouponValidateDto.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/filter/AuthenticationFilter.java, order/src/main/java/com/sparta/hotdeal/order/presentation/controller/BasketController.java, order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java, order/src/main/resources/application.yml, payment/src/main/java/com/sparta/hotdeal/payment/application/port/OrderClientPort.java, payment/src/main/java/com/sparta/hotdeal/payment/application/service/PaymentService.java, payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/adapter/OrderClientAdapter.java, payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/client/OrderClient.java, payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/config/OrderClientConfig.java, payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/config/SwaggerConfig.java, payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/dto/order/req/ReqPutOrderDto.java, payment/src/main/java/com/sparta/hotdeal/payment/infrastructure/exception/decoder/OrderClientErrorDecoder.java, payment/src/main/java/com/sparta/hotdeal/payment/presentation/controller/PaymentController.java, payment/src/main/resources/application.yml
- feature/88/update-order-status -> develop
- Resolves #88 
- Order status 수정 api 구현
- Payment OrderClient 구현 후 결제 승인 후 주문 상태 변경 api 호출
- payment swagger 추가
=> Payment 결제 승인 시 주문 상태 변경 구현 및 Swagger 추가

payment/src/main/resources/application-local.yml, payment/src/main/resources/application-prod.yml
- chore/93/docker-setup -> develop
- Resolves #93
- payment application.yml 스키마 이름 오타 수정
- 오타 수정입니다.
=> payment application.yml 스키마 이름 오타 수정

docker-compose.yml
- chore/93/docker-setup -> develop
- Resolves #93 
- docker-compose의 gateway 환경변수 누락 수정 (#93)
- 누락된 부분 추가했습니다.
=> docker-compose의 gateway 환경변수 누락 수정 (#93)

order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/req/ReqPostOrderDto.java, order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/adapter/CouponClientAdapter.java, order/src/main/java/com/sparta/hotdeal/order/infrastructure/filter/AuthenticationFilter.java, order/src/main/java/com/sparta/hotdeal/order/presentation/controller/OrderController.java
- feature/88/update-order-status -> develop
- Resolves 이슈 번호
- counponId null일때 버그 수정
=> Order couponId null 처리 if문 추가

order/src/main/java/com/sparta/hotdeal/order/application/dtos/order/res/ResPostOrderDto.java, order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java
- feature/88/update-order-status -> develop
- Resolves #88 
- 결제 요청 주석 처리
=> Order 결제 요청 호출 메서드 주석 처리

product/src/main/java/com/sparta/hotdeal/product/application/service/ProductService.java, product/src/main/java/com/sparta/hotdeal/product/application/service/ReviewService.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/Product.java
- feature/99/product-init-value
- Resolves #99 
- Product 도메인 내 ratingSum, reviewCnt 초기값 추가
=> Product 도메인 내 ratingSum, reviewCnt 초기값 추가

order/src/main/java/com/sparta/hotdeal/order/application/service/order/OrderService.java
- fix/101/fix-kakao-ready -> develop
- Resolves #101 
- .env 환경 변수 수정
- 주문 생성 시 결제 요청 함수 주석 해제
=> Order 결제 요청 오류 수정

user/src/main/java/com/sparta/hotdeal/user/infrastructure/config/AsyncConfig.java, user/src/main/java/com/sparta/hotdeal/user/infrastructure/service/MailServiceImpl.java
- refactor/112/async-email-user -> develop
- Resolves #112
- AsyncConfig 추가
- 이메일 발송 메서드에 Async 어노테이션 추가
- 응답 시간이 상당히 빨라졌습니다(4.18s -> 276ms). 비율로 따지면 약 93.39% 빨라졌습니다.
- AsyncConfig의 위치가 애매한데, infrastruceture에 두기에는 외부 의존성이 아니라 springboot에 포함된 요소이기 때문입니다. 질문 후 처리하겠습니다.
=> 이메일 인증 비동기 처리 구현

company/build.gradle, company/src/main/resources/logback.xml, coupon/build.gradle, coupon/src/main/resources/logback.xml, gateway/build.gradle, gateway/src/main/resources/logback.xml, order/build.gradle, order/src/main/resources/logback.xml, payment/build.gradle, payment/src/main/resources/logback.xml, product/build.gradle, product/src/main/resources/logback.xml, user/src/main/resources/logback.xml
로그 모니터링 시스템 구축 테스트
- feature/105/monitoring-grafana -> develop
- Resolves #105 
- 그라파나 로그 모니터링 구축 완료
- WARN, ERROR 로그만 나오도록 설정했습니다.
- 의존성을 추가하신 경우 충돌이 발생할 수 있습니다. 충돌이 날 경우 제가 추가한 monitoring 의존성들을 모두 추가해주시고, 각자 사용하시던 build.gradle 파일로 머지하도록 하시면 될 것 같습니다.
=> 로그 모니터링 시스템 구축 테스트

coupon/build.gradle, coupon/src/main/java/com/sparta/hotdeal/coupon/CouponApplication.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/ErrorCode.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/exception/GlobalExceptionHandler.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponIssueHelper.java, coupon/src/main/java/com/sparta/hotdeal/coupon/application/service/CouponService.java, coupon/src/main/java/com/sparta/hotdeal/coupon/domain/entity/CouponInfo.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/config/RedissonConfig.java, coupon/src/main/java/com/sparta/hotdeal/coupon/infrastructure/filter/AuthenticationFilter.java, coupon/src/main/java/com/sparta/hotdeal/coupon/presentation/controller/CouponController.java, coupon/src/main/resources/application-local.yml, coupon/src/main/resources/application-prod.yml
- refactor/111/coupon-issue-redisson -> develop
- Resolves #111 
- 기존 코드 성능 테스트
- 낙관적 락 구현 및 성능 테스트
- Redis 분산락 구현 및 성능 테스트
- Redis 분산락 코드 적용
- Redisson 의존성 추가
- yml에 Redis 설정 추가
- 문서화
- [선착순 쿠폰 발급 API 성능 테스트 문서](https://stingy-banjo-fdd.notion.site/API-17c8e7a4cf428086a574ee7c27a37118)
- 문서화 열심히 했습니다.. 많이 길긴한데 읽어주시면 뿌듯할 것 같습니다 🥲🥲
=> 선착순 쿠폰 발급 성능 테스트 및 개선

product/build.gradle, product/src/main/java/com/sparta/hotdeal/product/application/service/product/ProductIndexService.java, product/src/main/java/com/sparta/hotdeal/product/application/service/product/ProductService.java, product/src/main/java/com/sparta/hotdeal/product/domain/entity/product/ProductDocument.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/config/ElasticsearchConfig.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/kafka/ProductKafkaConsumer.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductSearchRepository.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductSearchRepositoryCustom.java, product/src/main/java/com/sparta/hotdeal/product/infrastructure/repository/product/ProductSearchRepositoryCustomImpl.java, product/src/main/resources/application-local.yml, product/src/main/resources/application-prod.yml, product/src/main/resources/application.yml, product/src/test/java/com/sparta/hotdeal/product/ProductControllerTest.java, product/src/test/java/com/sparta/hotdeal/product/PromotionControllerTest.java
- refactor/120/refactor-product -> develop
- Resolves #120 
- 상품 목록 조회 api 에 대해 엘라스틱 서치 적용
- ProductControllerTest, PromotionControllerTest 작성
- 상품 재고 관리 관련 카프카 key, message 수정
=> Product 목록 조회 고도화 및 테스트 코드 작성

user/src/main/java/com/sparta/hotdeal/user/application/service/AuthService.java, user/src/main/java/com/sparta/hotdeal/user/libs/config/AsyncConfig.java, user/src/main/java/com/sparta/hotdeal/user/libs/util/JwtUtil.java
- chore/130/package-user -> develop
- Resolves #130 
- JwtUtil, AsyncConfig를 libs 패키지로 이동
- 패키지 구조에 대해 피드백 받은 후 적용한 내용입니다.
- AsyncConfig는 Spring에 포함된 부분이고, JwtUtil은 직접적인 비즈니스 로직은 아니지만 연관이 있는 Util에 속합니다. 이런 것들을 모아 libs 패키지에 포함시키라는 피드백을 받았습니다.
- 그래서 최상위에 application, libs, infrastructure, presentation 4개의 패키지가 존재합니다.
=> User 서비스 일부 클래스 패키지 변경

order/src/main/resources/application-local.yml, order/src/main/resources/application-prod.yml, payment/src/main/resources/application-local.yml, payment/src/main/resources/application-prod.yml
- consumer, producer bootstrap-servers ENDPOINT 추가
- fix/140/fix-order-payment -> develop
- Resolves #140 
- order application 파일 consumer, producer kafka endpoint 설정 추가
=> Order application 파일 consumer, producer kafka endpoint 설정 추가

company/src/main/java/com/sparta/hotdeal/company/application/service/CompanyService.java
- feature/이슈번호/(create · read · update · delete)-도메인명 -> develop
- Resolves #142 
- Company 트랜잭션 누락 추가
=> Company 트랜잭션 누락 추가

product/src/main/java/com/sparta/hotdeal/product/application/service/promotion/PromotionService.java, product/src/main/resources/application-prod.yml
- refactor/120/refactor-promotion -> develop
- Resolves #120 
- yml 카프카 환경변수 추가
- 프로모션 수정할 때 시간 검증 추가
=> 프로모션 수정 리팩토링 및 카프카 관련 yml 수정

.github/workflows/actions.yml
- feature/이슈번호/(create · read · update · delete)-도메인명 -> develop
- Resolves #121 
- 깃허브 액션 워크플로우 파일 작성
- main 브랜치 커밋 감지 시 ec2의 docker compose를 실행
- compose는 빌드 및 실행을 할 수 있도록 작성되어 있으며, 빌드 이미지는 ec2에 저장됨
- compose를 실행하는 부분만 자동화하도록 작성했습니다.
- 추후에 빌드를 github actions에서 수행하고(CI), 이미지를 ECR에 저장한 후, 그것을 pull 해서 사용하도록 워크플로우 파일 및 compose 파일 수정이 필요합니다.
=> chore: github actions 워크플로우 파일 작성 (#121)

.github/workflows/actions.yml, docker-compose.yml
- chore/121/cicd-docker -> develop
- Resolves #121 
- 워크플로우에 빌드 및 ECR 푸시 과정 추가
- docker-compose.yml에서 build를 제거하고 images를 정의해 ECR에서 이미지를 가져오도록 수정
- 빌드를 깃허브 액션에서 수행하도록(CI) 해당 내용을 추가했습니다.
- 빌드된 이미지는 ECR로 푸시되며, 배포 시(CD) 이 이미지를 가져오도록 변경했습니다.
=> github actions 워크플로우에 빌드 추가 및 docker-compsoe.yml 수정
